branch:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

stages:
  - name: 'Ruby1.9.3'
  - name: 'Ruby2.3.8'
  - name: 'Ruby2.4.5'
  - name: 'Ruby2.5.3'
  - name: 'Ruby2.6.2'

jobs:
  include:
    - stage: 'Ruby1.9.3'
      language: ruby
      cache: bundler
      sudo: required
      rvm: 1.9.3
      gemfile: Gemfile.rubyv1
      before_install:
        - gem install bundler -v 1.9
        - rm -rf Gemfile.lock
      install:
        - bundle install
        - yes n | gem install json -v 1.8.6
        - yes n | gem uninstall json -v 2.3.0
      script:
        - ruby tests/test_all_tests.rb
      after_success: "coveralls"

    - stage: 'Ruby2.3.8'
      language: ruby
      cache: bundler
      sudo: required
      rvm: 2.3.8
      before_install:
        - gem update --system
        - gem install bundler
        - rm -rf Gemfile.lock
      install:
        - bundle install
      script:
        - ruby tests/test_all_tests.rb
      before_script: "rubocop lib/"
      after_success: "coveralls"

    - stage: 'Ruby2.4.5'
      language: ruby
      cache: bundler
      sudo: required
      rvm: 2.4.5
      before_install:
        - gem update --system
        - gem install bundler
        - rm -rf Gemfile.lock
      install:
        - bundle install
      script:
        - ruby tests/test_all_tests.rb
      before_script: "rubocop lib/"
      after_success: "coveralls"

    - stage: 'Ruby2.5.3'
      language: ruby
      cache: bundler
      sudo: required
      rvm: 2.5.3
      before_install:
        - gem update --system
        - gem install bundler
        - rm -rf Gemfile.lock
      install:
        - bundle install
      script:
        - ruby tests/test_all_tests.rb
      before_script: "rubocop lib/"
      after_success: "coveralls"

    - stage: 'Ruby2.6.2'
      language: ruby
      cache: bundler
      sudo: required
      rvm: 2.6.2
      before_install:
        - gem update --system
        - gem install bundler
        - rm -rf Gemfile.lock
      install:
        - bundle install
      script:
        - ruby tests/test_all_tests.rb
      before_script: "rubocop lib/"
      after_success: "coveralls"
